//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeDolan3._0.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NewDolan2Entities : DbContext
    {
        public NewDolan2Entities()
            : base("name=NewDolan2Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<AspNetRoles> AspNetRoles { get; set; }
        public virtual DbSet<AspNetUserClaims> AspNetUserClaims { get; set; }
        public virtual DbSet<AspNetUserLogins> AspNetUserLogins { get; set; }
        public virtual DbSet<AspNetUsers> AspNetUsers { get; set; }
        public virtual DbSet<Milestone> Milestone { get; set; }
        public virtual DbSet<Permisos> Permisos { get; set; }
        public virtual DbSet<Project> Project { get; set; }
        public virtual DbSet<Scenario> Scenario { get; set; }
        public virtual DbSet<Sprint> Sprint { get; set; }
        public virtual DbSet<Users> Users { get; set; }
        public virtual DbSet<UserStory> UserStory { get; set; }
        public virtual DbSet<Tasks> Tasks { get; set; }
    }
}
