//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeDolan3._0.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;
    using System.Data.Entity;
    using System.Linq;


    public partial class ProjectTaskInt
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTaskInt()
        {
            this.Milestones = new HashSet<Milestone>();
        }

        [Display(Name = "ID de Proyecto")]
        public string ProjectID { get; set; }
        [Display(Name = "ID de String")]
        public int SprintID { get; set; }
        [Display(Name = "ID de Historia de Usuario")]
        public string StoryID { get; set; }
        [Display(Name = "ID de Tarea")]
        public string TaskID { get; set; }
        [Required(ErrorMessage = "Sin una descripcion la tarea no puede existir.")]
        public string Descripcion { get; set; }
        [Display(Name = "Tiempo estimado")]
        public Nullable<int> EstimateTime { get; set; }
        [Display(Name = "Prioridad")]
        public Nullable<int> Priority { get; set; }
        [Display(Name = "Estado")]
        public string Estado { get; set; }
        [Display(Name = "Usuario")]
        public string UserID { get; set; }

        public virtual UserStory UserStory { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Milestone> Milestones { get; set; }
    }
}