//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeDolan3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTask
    {
        public string ProjectID { get; set; }
        public int SprintID { get; set; }
        public string StoryID { get; set; }
        public string TaskID { get; set; }
        public string Descripcion { get; set; }
        public Nullable<int> EstimateTime { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Estado { get; set; }
    
        public virtual UserStory UserStory { get; set; }
        public virtual User User { get; set; }
    }
}
