//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeDolan3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class role_permit
    {
        public string fk_role_id { get; set; }
        public int fk_permit_code { get; set; }
    
        public virtual AspNetRoles AspNetRoles { get; set; }
        public virtual AspNetRoles AspNetRoles1 { get; set; }
        public virtual Permisos Permisos { get; set; }
        public virtual Permisos Permisos1 { get; set; }
    }
}
