//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeDolan3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Scenario
    {
        public string ProjectID { get; set; }
        public int SprintID { get; set; }
        public string StoryID { get; set; }
        public int ScenarioNumber { get; set; }
        public string Resultado { get; set; }
        public string Event { get; set; }
        public string AcceptanceCriteria { get; set; }
        public string Context { get; set; }
    
        public virtual UserStory UserStory { get; set; }
    }
}
