//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IngeDolan3._0.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserStory
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserStory()
        {
            this.Scenario = new HashSet<Scenario>();
            this.Tasks = new HashSet<Tasks>();
        }
    
        public string ProjectID { get; set; }
        public int SprintID { get; set; }
        public string StoryID { get; set; }
        public string Modulo { get; set; }
        public string ID { get; set; }
        public Nullable<int> Priorities { get; set; }
        public string ClientRole { get; set; }
        public Nullable<int> Estimation { get; set; }
        public string Reason { get; set; }
        public string Funtionality { get; set; }
        public string Alias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Scenario> Scenario { get; set; }
        public virtual Sprint Sprint { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tasks> Tasks { get; set; }
    }
}
